### ISSUE TITLE
Incompatibility with PagingKit (1.14.0)

### ISSUE THREAD

**Issue by Astamariy** [kazuhiro4949/RxPagingKit#10]
Hi, @kazuhiro4949 !

RxPagingKit has ios.deployment_target = '8.0' in its pod spec file, but since 1.14.0 PagingKit has ios.deployment_target = '9.0'.

It leads to **Compiling for iOS 8.0, but module 'PagingKit' has a minimum deployment target of iOS 9.0** Swift Compiler Error.

I can suggest hot fix: just update RxPagingKit ios.deployment_target to '9.0' value.

Thank you for this awesome Rx Extension 😊

**Comment by kazuhiro4949** [comment]
@Astamariy Thanks :p I fixed podspec.
